Add notebooks from QA-ML Team.
nsmq-ai/nsmqai pull request #59
Opened 2023-07-30 10:57 UTC by naafidasana

# Description
We've included a notebook to generate embeddings database for the Cohere Simple Wikipedia dataset, and another to use the Falcon model for inference on NSMQ riddles (plus an API endpoint to the model).

@wsedor of 1 person at minimum to review the proposed changes

2023-07-31 22:38 UTC, wsedor commented on question-answering/Embeddings_Database_For_Simple_Wikipedia_Passages.ipynb
@naafidasana where did we get this file from and do we have the license to upload it to our repo if it was not generated from us?

2023-08-01 00:33 UTC, naafidasana commented on question-answering/Embeddings_Database_For_Simple_Wikipedia_Passages.ipynb
We wrote the code in the notebook ourselves.
For the dataset that was used to build the embeddings database, we obtained that from the Cohere Wikipedia dataset (The Simple English Wikipedia split, particularly, which contains approximately 500k passages).
The dataset is governed by the Apache 2.0 License, so, yes, we can upload it to our repo.

2023-08-03 14:48 UTC, Nanayeb34 reviewed
Hello @naafidasana , can you exclude the outputs of the cells when you are uploading the file. Also, can you comment the portion of the ngrok that will let the user know they are to type in their auth token there instead of  just leaving it blank.

2023-08-03 14:58 UTC, Nanayeb34 reviewed
@naafidasana can you remove the output of the cells and delete the cell that contained no code in the middle of the work

2023-08-03 14:58 UTC, Nanayeb34 commented on question-answering/Embeddings_Database_For_Simple_Wikipedia_Passages.ipynb
@naafidasana can you remove the output of the cells and delete the cell that contained no code in the middle of the work

2023-08-04 00:44 UTC, kojomensahonums requested changes

2023-08-04 00:44 UTC, kojomensahonums commented on question-answering/Embeddings_Database_For_Simple_Wikipedia_Passages.ipynb
@naafidasana kindly reformat some of the markdowns used. Headings will do for notes you described as steps. For the notes you had a title and underneath points, say point 1 to 3. You should reformat the main heading.

Some of the markdowns also need to be comments inside the cells. An example is "install required packages" note as markdown.

2023-08-04 14:08 UTC, wsedor commented
@naafidasana I also noticed the name of your branch is `qa-ml`. in future please follow the PR guidelines here https://github.com/nsmq-ai/nsmqai/blob/main/docs/CONTRIBUTING.md#pull-requests

2023-08-10 19:09 UTC, naafidasana commented on question-answering/Embeddings_Database_For_Simple_Wikipedia_Passages.ipynb
@Nanayeb34 
@kojomensahonums 
Kindly review.
I've resolved the issues (hopefully all of them).

2023-08-10 21:16 UTC, Nanayeb34 approved these changes

2023-08-10 21:49 UTC, kojomensahonums commented on question-answering/nsmq_falcon.ipynb
Good job so far.
A quick one, for the cell that requires users to input their access token, can you provide a comment so users are prompted what to do? 
@Nanayeb34 used this in his notebook, I think it would be a great addition:

#Replace comment section below with your auth token
`!ngrok config add-authtoken #place your access token here`

2023-08-13 12:16 UTC, closed without merging